name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: testFinalSumPrint
      id: testfinalsumprint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testFinalSumPrint
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --warning-mode all --tests "Prog31Test.testFinalSumPrint"
        timeout: 10
        max-score: 3
    - name: testDoNotStopWithManyInputs
      id: testdonotstopwithmanyinputs
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testDoNotStopWithManyInputs
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog31Test.testDoNotStopWithManyInputs"
        timeout: 10
        max-score: 4
    - name: testInitialization
      id: testinitialization
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testInitialization
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog31Test.testInitialization"
        timeout: 10
        max-score: 3
    - name: testSecondPrint
      id: testsecondprint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testSecondPrint
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog31Test.testSecondPrint"
        timeout: 10
        max-score: 3
    - name: testLastPrint
      id: testlastprint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testLastPrint
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog31Test.testLastPrint"
        timeout: 10
        max-score: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTFINALSUMPRINT_RESULTS: "${{steps.testfinalsumprint.outputs.result}}"
        TESTDONOTSTOPWITHMANYINPUTS_RESULTS: "${{steps.testdonotstopwithmanyinputs.outputs.result}}"
        TESTINITIALIZATION_RESULTS: "${{steps.testinitialization.outputs.result}}"
        TESTSECONDPRINT_RESULTS: "${{steps.testsecondprint.outputs.result}}"
        TESTLASTPRINT_RESULTS: "${{steps.testlastprint.outputs.result}}"
      with:
        runners: testfinalsumprint,testdonotstopwithmanyinputs,testinitialization,testsecondprint,testlastprint
